import { Manrope, Marcellus, Inter, Raleway } from 'next/font/google'
import './globals.css'

const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' })
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' })
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const marcellus = Marcellus({subsets:['latin'], weight: ['400'], variable: '--font-marcellus' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${marcellus.variable} ${inter.variable} ${raleway.variable}`}>{children}</body>
    </html>
  )
}
